# Generated by Django 2.0.8 on 2018-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(max_length=100)),
                ('update_date', models.DateTimeField(max_length=100)),
                ('owner', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('store_phone', models.CharField(max_length=200)),
                ('store_address', models.CharField(max_length=200)),
                ('rent', models.IntegerField(default=0)),
                ('perc_commission', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
