# Generated by Django 2.0.8 on 2018-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0002_auto_20181105_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='expositor@expositor.com', max_length=254),
        ),
    ]
