# Generated by Django 2.0.8 on 2018-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0003_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('colour', models.CharField(default='nao consta', max_length=200)),
            ],
        ),
    ]
