# Generated by Django 2.0.8 on 2018-12-01 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda_admin', '0004_payment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True, max_length=100)),
                ('qtd', models.IntegerField(default=1)),
                ('obs', models.CharField(max_length=200)),
                ('is_troca', models.BooleanField(default=False)),
                ('un_price', models.FloatField(blank=True, default=0, null=True)),
                ('final_price', models.FloatField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_admin.Customer')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_admin.Payment')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colour', to='tienda_admin.Product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='tienda_admin.Product')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
