# Generated by Django 2.0.8 on 2018-12-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0005_dailyinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyinput',
            old_name='product_color',
            new_name='product_colour',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
