# Generated by Django 2.0.8 on 2018-12-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0007_auto_20181203_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinput',
            name='obs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyinput',
            name='product_colour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colour', to='tienda_admin.Product'),
        ),
        migrations.AlterField(
            model_name='dailyinput',
            name='product_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='tienda_admin.Product'),
        ),
    ]
