# Generated by Django 2.0.8 on 2018-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0008_auto_20181203_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinput',
            name='create_date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
