# Generated by Django 2.0.8 on 2018-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0009_auto_20181203_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinput',
            name='create_date',
            field=models.DateField(max_length=100),
        ),
    ]
