# Generated by Django 2.0.8 on 2018-12-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0011_auto_20181203_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinput',
            name='product_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colour', to='tienda_admin.Product'),
        ),
    ]
