# Generated by Django 2.0.8 on 2018-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0012_auto_20181203_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinput',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyinput',
            name='un_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
