# Generated by Django 2.0.8 on 2018-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_admin', '0013_auto_20181205_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
